# Usa una imagen base de Node.js para el entorno de desarrollo
FROM node:20-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de definición de dependencias
COPY package.json package-lock.json ./

# Instala las dependencias (incluyendo devDependencies)
RUN npm install

# Expone el puerto que Vite usará para el servidor de desarrollo
EXPOSE 3000

# El comando por defecto para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]