# --- Etapa 1: Build ---
# Usamos una imagen de Node.js completa que incluye herramientas de compilación.
FROM node:20 as build

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de dependencias y los instalamos
COPY package.json package-lock.json ./
RUN npm install

# Copiamos todo el código fuente de la aplicación
COPY . .

# Ejecutamos el script de build para generar los archivos de producción
RUN npm run build


# --- Etapa 2: Runner ---
# Partimos de una imagen de Node.js mucho más ligera para producción.
FROM node:20-alpine

WORKDIR /app

# Copiamos solo las dependencias de producción desde la etapa de build
COPY --from=build /app/node_modules ./node_modules
# Copiamos los artefactos compilados (la carpeta dist) desde la etapa de build
COPY --from=build /app/dist ./dist

# Expone el puerto 3000 donde corre el servidor de Express
EXPOSE 3000

# El comando para iniciar la aplicación en modo producción
CMD ["node", "dist/server.cjs"]