export const SEED_SCREENS = [
  {
    id: "sc-01",
    nombre: "Sarmiento y 9 de Julio",
    zona: "Centro",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 14200,
    precio: 95000,
    status: "Activo",
    lat: -32.8894,
    lng: -68.8458,
    nota: "Esquina comercial neurálgica de máximo tránsito peatonal y comercial.",
    dimensiones: "3.5m x 2.0m (7.00m²)",
    brillo: "5,500 nits (Auto-Dimming)",
    refreshRate: "3,840 Hz (Flicker-Free)",
    formato: "MP4, JPG, HTML5",
    cobertura: "Alta densidad peatonal y turística"
  },
  {
    id: "sc-02",
    nombre: "Palmares Open Mall",
    zona: "Palmares",
    tipo: "Mixto",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 22500,
    precio: 145000,
    status: "Activo",
    lat: -32.9121,
    lng: -68.8306,
    nota: "Acceso principal al centro comercial. Cobertura premium vehicular y peatonal.",
    dimensiones: "5.0m x 3.0m (15.00m²)",
    brillo: "6,500 nits (High-Contrast)",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Público ABC1 de alto nivel de consumo"
  },
  {
    id: "sc-03",
    nombre: "Las Heras y Mitre",
    zona: "Las Heras",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 8800,
    precio: 68000,
    status: "Activo",
    lat: -32.8716,
    lng: -68.8388,
    nota: "Zona de alto tránsito comercial local e intercomunal.",
    dimensiones: "3.0m x 2.0m (6.00m²)",
    brillo: "5,000 nits",
    refreshRate: "1,920 Hz",
    formato: "MP4, JPG",
    cobertura: "Comercio local y cercanía"
  },
  {
    id: "sc-04",
    nombre: "Av. Arístides frente al Parque",
    zona: "Ciudad",
    tipo: "Vehicular",
    categoria: "Tradicionales",
    ciudad: "Mendoza",
    impactos: 31000,
    precio: 185000,
    status: "Activo",
    lat: -32.8908,
    lng: -68.8762,
    nota: "Soporte monumental estático iluminado en el polo gastronómico más importante.",
    dimensiones: "7.0m x 3.0m (21.00m²)",
    brillo: "Iluminación LED Backlight",
    refreshRate: "N/A",
    formato: "Lona Tensada Vinílica",
    cobertura: "Público joven, nocturno y polo estudiantil"
  },
  {
    id: "sc-05",
    nombre: "Guaymallén Centro",
    zona: "Guaymallén",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 11400,
    precio: 78000,
    status: "Activo",
    lat: -32.8955,
    lng: -68.8212,
    nota: "Pantalla LED ubicada en zona de supermercados y polo comercial de Guaymallén.",
    dimensiones: "4.0m x 2.5m (10.00m²)",
    brillo: "5,500 nits",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Gran flujo residencial diario"
  },
  {
    id: "sc-06",
    nombre: "Maipú Ruta 7",
    zona: "Maipú",
    tipo: "Vehicular",
    categoria: "Tradicionales",
    ciudad: "Mendoza",
    impactos: 19600,
    precio: 112000,
    status: "Activo",
    lat: -32.9812,
    lng: -68.7757,
    nota: "Cartel monumental estático en ruta de conexión al aeropuerto y bodegas.",
    dimensiones: "8.0m x 4.0m (32.00m²)",
    brillo: "Luz Frontlight LED",
    refreshRate: "N/A",
    formato: "Lona Frontlight",
    cobertura: "Logística, turismo y bodegas"
  },
  {
    id: "sc-07",
    nombre: "Villanueva Gomensoro",
    zona: "Las Heras",
    tipo: "Mixto",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 9300,
    precio: 72000,
    status: "Activo",
    lat: -32.8658,
    lng: -68.8415,
    nota: "Ubicación mixta residencial-comercial con excelente ángulo de lectura.",
    dimensiones: "3.5m x 2.0m (7.00m²)",
    brillo: "5,000 nits",
    refreshRate: "1,920 Hz",
    formato: "MP4, JPG",
    cobertura: "Tránsito residencial interurbano"
  },
  {
    id: "sc-08",
    nombre: "Godoy Cruz Belgrano",
    zona: "Godoy Cruz",
    tipo: "Vehicular",
    categoria: "Tradicionales",
    ciudad: "Mendoza",
    impactos: 25800,
    precio: 155000,
    status: "Activo",
    lat: -32.9246,
    lng: -68.8488,
    nota: "Monolito iluminado de gran visibilidad en el principal eje de Godoy Cruz.",
    dimensiones: "10.0m x 4.0m (40.00m²)",
    brillo: "Foco LED Frontal",
    refreshRate: "N/A",
    formato: "Lona Frontlight Premium",
    cobertura: "Tránsito automotor y comercial intenso"
  },
  {
    id: "sc-09",
    nombre: "Chacras de Coria Acceso",
    zona: "Luján",
    tipo: "Vehicular",
    categoria: "Tradicionales",
    ciudad: "Mendoza",
    impactos: 16700,
    precio: 125000,
    status: "Activo",
    lat: -33.0158,
    lng: -68.8642,
    nota: "Soporte de ingreso al polo premium residencial y turístico de Chacras.",
    dimensiones: "8.0m x 3.0m (24.00m²)",
    brillo: "Iluminación LED Externa",
    refreshRate: "N/A",
    formato: "Lona Vinílica",
    cobertura: "Público selecto, turismo y barrios privados"
  },
  {
    id: "sc-10",
    nombre: "Terminal de Ómnibus",
    zona: "Centro",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Mendoza",
    impactos: 18400,
    precio: 118000,
    status: "Activo",
    lat: -32.8868,
    lng: -68.8284,
    nota: "Pantalla de gran formato con alto caudal de pasajeros las 24 horas.",
    dimensiones: "6.0m x 3.0m (18.00m²)",
    brillo: "6,000 nits (Auto-Dimming)",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Viajeros de media y larga distancia, transeúntes"
  },
  {
    id: "sc-11",
    nombre: "LeadMóvil Mendoza Express",
    zona: "Metropolitana",
    tipo: "Móvil",
    categoria: "LED Móvil",
    ciudad: "Mendoza",
    impactos: 38000,
    precio: 160000,
    status: "Activo",
    lat: -32.8894,
    lng: -68.8458,
    nota: "Exclusiva pantalla móvil de alta definición con recorrido lineal constante.",
    dimensiones: "4.0m x 2.0m Doble Cara",
    brillo: "7,500 nits (UHD Outdoor)",
    refreshRate: "3,840 Hz (Flicker-Free)",
    formato: "MP4, JPG, Transmisión en Vivo",
    cobertura: "Principales avenidas y ejes recreacionales",
    horarios: "10:00 a 14:00 y 17:00 a 21:00 hs",
    ruta: JSON.stringify([
      { lat: -32.8894, lng: -68.8458, nombre: "Plaza Independencia (Inicio)" },
      { lat: -32.8897, lng: -68.8427, nombre: "España y Peatonal Sarmiento" },
      { lat: -32.8940, lng: -68.8398, nombre: "Av. Colón y San Martín (Centro)" },
      { lat: -32.8908, lng: -68.8552, nombre: "Arístides Villanueva y Belgrano" },
      { lat: -32.8904, lng: -68.8643, nombre: "Arístides Villanueva y Paso de los Andes" },
      { lat: -32.8891, lng: -68.8690, nombre: "Portones del Parque Gral San Martín" },
      { lat: -32.8872, lng: -68.8803, nombre: "Fuente de los Continentes (Fin)" }
    ])
  },
  {
    id: "ba-01",
    nombre: "Av. 9 de Julio y Corrientes",
    zona: "Obelisco",
    tipo: "Vehicular",
    categoria: "Pantallas LED",
    ciudad: "Buenos Aires",
    impactos: 75000,
    precio: 220000,
    status: "Activo",
    lat: -34.6037,
    lng: -58.3816,
    nota: "Pantalla monumental frente al Obelisco, máxima penetración nacional y visibilidad garantizada.",
    dimensiones: "12.0m x 8.0m (96.00m²)",
    brillo: "8,500 nits (Extreme UHD)",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG, Transmisión en Vivo",
    cobertura: "La esquina neurálgica de mayor tráfico del país"
  },
  {
    id: "ba-02",
    nombre: "Av. del Libertador y Av. Callao",
    zona: "Recoleta",
    tipo: "Mixto",
    categoria: "Pantallas LED",
    ciudad: "Buenos Aires",
    impactos: 42000,
    precio: 180000,
    status: "Activo",
    lat: -34.5885,
    lng: -58.3889,
    nota: "Corredor vial ultra premium conectando zona norte con el centro cívico y comercial.",
    dimensiones: "8.0m x 4.0m (32.00m²)",
    brillo: "7,500 nits (Flicker-Free)",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Target ABC1 ejecutivo, turístico y corporativo"
  },
  {
    id: "ba-03",
    nombre: "Puerto Madero Dique 3",
    zona: "Puerto Madero",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Buenos Aires",
    impactos: 28000,
    precio: 150000,
    status: "Activo",
    lat: -34.6076,
    lng: -58.3643,
    nota: "Ubicación exclusiva en el dique financiero, residencial y de esparcimiento de lujo.",
    dimensiones: "5.0m x 3.0m (15.00m²)",
    brillo: "6,000 nits",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Ejecutivos, turistas y público de alto poder adquisitivo"
  },
  {
    id: "ba-04",
    nombre: "Av. Cabildo y Juramento",
    zona: "Belgrano",
    tipo: "Peatonal",
    categoria: "Pantallas LED",
    ciudad: "Buenos Aires",
    impactos: 35000,
    precio: 130000,
    status: "Activo",
    lat: -34.5621,
    lng: -58.4566,
    nota: "Esquina comercial de Belgrano de altísima circulación peatonal y trasbordo constante.",
    dimensiones: "6.0m x 4.0m (24.00m²)",
    brillo: "6,500 nits",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Flujo peatonal masivo constante"
  },
  {
    id: "ba-05",
    nombre: "Autopista Panamericana km 18",
    zona: "Norte",
    tipo: "Vehicular",
    categoria: "Tradicionales",
    ciudad: "Buenos Aires",
    impactos: 92000,
    precio: 250000,
    status: "Activo",
    lat: -34.4988,
    lng: -58.5322,
    nota: "Soporte estático de escala gigante en el acceso principal de mayor volumen de Zona Norte.",
    dimensiones: "15.0m x 5.0m (75.00m²)",
    brillo: "Doble Faz Backlight Iluminado",
    refreshRate: "N/A",
    formato: "Lona Backlight",
    cobertura: "Commuters diarios y logística interprovincial"
  },
  {
    id: "ba-06",
    nombre: "LeadMóvil Buenos Aires Express",
    zona: "Metropolitana",
    tipo: "Móvil",
    categoria: "LED Móvil",
    ciudad: "Buenos Aires",
    impactos: 55000,
    precio: 210000,
    status: "Activo",
    lat: -34.6037,
    lng: -58.3816,
    nota: "Unidad móvil premium recorriendo los distritos comerciales de Palermo, Recoleta y Retiro.",
    dimensiones: "5.0m x 2.5m Doble Cara",
    brillo: "8,000 nits",
    refreshRate: "3,840 Hz",
    formato: "MP4, JPG",
    cobertura: "Zonas de gran concentración comercial y de ocio",
    horarios: "11:00 a 15:00 y 18:00 a 22:00 hs",
    ruta: JSON.stringify([
      { lat: -34.6037, lng: -58.3816, nombre: "Obelisco (Inicio)" },
      { lat: -34.5885, lng: -58.3889, nombre: "Av. Libertador y Callao" },
      { lat: -34.5711, lng: -58.4233, nombre: "Plaza Italia (Palermo)" },
      { lat: -34.5830, lng: -58.4110, nombre: "Palermo Soho (Honduras y Serrano)" },
      { lat: -34.5975, lng: -58.3855, nombre: "Av. Santa Fe y 9 de Julio (Fin)" }
    ])
  }
];

export const INITIAL_CLIENTES = [
  {
    id: "cl-01",
    nombre: "Ana de la Cruz",
    empresa: "Toyota Mendoza",
    email: "ana.cruz@toyotamendoza.com.ar",
    telefono: "+54 261 455-1212",
    categoria: "Corporativo",
    campanasActivas: 2,
    totalInversion: 1450000
  },
  {
    id: "cl-02",
    nombre: "Carlos Bianchi",
    empresa: "Agencia JWT Argentina",
    email: "carlos.bianchi@jwt.com",
    telefono: "+54 11 4899-0099",
    categoria: "Agencia",
    campanasActivas: 3,
    totalInversion: 3820000
  },
  {
    id: "cl-03",
    nombre: "Martín Palermo",
    empresa: "Cencosud S.A.",
    email: "palermo@cencosud.com.ar",
    telefono: "+54 261 511-2233",
    categoria: "Corporativo",
    campanasActivas: 1,
    totalInversion: 980000
  },
  {
    id: "cl-04",
    nombre: "Sofía Martínez",
    empresa: "Franquicias Café Central",
    email: "sofia@cafecentral.com.ar",
    telefono: "+54 264 422-3344",
    categoria: "Directo",
    campanasActivas: 0,
    totalInversion: 420000
  }
];

export const INITIAL_MEDIAKITS = [
  {
    id: "mk-201",
    nombre: "Lanzamiento Toyota Hilux 2026",
    clienteId: "cl-01",
    clienteNombre: "Toyota Mendoza",
    ciudad: "Mendoza",
    screenIds: JSON.stringify(["sc-01", "sc-02", "sc-11"]),
    version: 2,
    estado: "Cotizando",
    fecha: "2026-07-28",
    presupuesto: 4000000,
    objetivo: "Branding de alta densidad vehicular y peatonal",
    comentarios: JSON.stringify([
      { id: "c-1", user: "Director Comercial", text: "Cliente solicita priorizar Palmares por flujo ABC1.", date: "2026-07-28 15:30" }
    ]),
    historial: JSON.stringify([
      { id: "h-1", action: "Creado por Comercial Ejec.", date: "2026-07-28 10:00", user: "Comercial Ejec." },
      { id: "h-2", action: "Agregada pantalla LeadMóvil Mendoza Express (sc-11)", date: "2026-07-28 14:15", user: "Director Comercial" }
    ]),
    soportesEdicionInline: JSON.stringify([
      { id: "sc-01", notas: "Pautado central de spots 15s cada 120s.", prioridad: "Alta", duracionSem: 4 },
      { id: "sc-02", notas: "Esquina premium Palmares, máxima nitidez.", prioridad: "Alta", duracionSem: 4 },
      { id: "sc-11", notas: "Recorrido dinámico por Arístides de 17h a 21h.", prioridad: "Media", duracionSem: 2 }
    ])
  },
  {
    id: "mk-202",
    nombre: "Campaña Institucional Cencosud - CABA",
    clienteId: "cl-03",
    clienteNombre: "Cencosud S.A.",
    ciudad: "Buenos Aires",
    screenIds: JSON.stringify(["ba-01", "ba-02"]),
    version: 1,
    estado: "Borrador",
    fecha: "2026-07-29",
    presupuesto: 6500000,
    objetivo: "Visibilidad extrema en el casco metropolitano",
    comentarios: JSON.stringify([]),
    historial: JSON.stringify([
      { id: "h-3", action: "Creado borrador preliminar", date: "2026-07-29 09:30", user: "Comercial Ejec." }
    ]),
    soportesEdicionInline: JSON.stringify([
      { id: "ba-01", notas: "Frente al Obelisco, pautado premium nocturno.", prioridad: "Alta", duracionSem: 2 },
      { id: "ba-02", notas: "Corredor Callao y Libertador para target ejecutivo.", prioridad: "Alta", duracionSem: 2 }
    ])
  },
  {
    id: "mk-203",
    nombre: "Pauta Estacional Mendoza - Retail PyME",
    clienteId: "cl-04",
    clienteNombre: "Franquicias Café Central",
    ciudad: "Mendoza",
    screenIds: JSON.stringify(["sc-01", "sc-03"]),
    version: 3,
    estado: "Aceptado",
    fecha: "2026-07-25",
    presupuesto: 1200000,
    objetivo: "Tracción de tráfico a locales del microcentro",
    comentarios: JSON.stringify([
      { id: "c-2", user: "Comercial Ejec.", text: "Cliente aceptó el descuento del 10% en el pack.", date: "2026-07-26 11:00" }
    ]),
    historial: JSON.stringify([
      { id: "h-4", action: "Creado", date: "2026-07-25 11:00", user: "Comercial Ejec." },
      { id: "h-5", action: "Aplicado descuento comercial del 10%", date: "2026-07-26 10:15", user: "Director Comercial" },
      { id: "h-6", action: "Aprobado por el cliente", date: "2026-07-27 16:00", user: "Comercial Ejec." }
    ]),
    soportesEdicionInline: JSON.stringify([
      { id: "sc-01", notas: "Cerca de Sarmiento, gran impacto peatonal.", prioridad: "Alta", duracionSem: 3 },
      { id: "sc-03", notas: "Plaza España, casco comercial.", prioridad: "Alta", duracionSem: 3 }
    ])
  }
];

export const INITIAL_LOGS = [
  { id: "lg-1", user: "Director Comercial", action: "Aprobó Cotización #QT-102 para Café Central", date: "Hoy, 12:45" },
  { id: "lg-2", user: "Comercial Ejec.", action: "Duplicó MediaKit #MK-201 (Hilux 2026)", date: "Hoy, 10:20" },
  { id: "lg-3", user: "Operaciones", action: "Bloqueó Pantalla sc-03 (Las Heras y Mitre) por limpieza LED", date: "Ayer, 16:30" },
  { id: "lg-4", user: "Administrador", action: "Actualizó tarifa base de Plaza Buenos Aires (+10% global)", date: "Hace 2 días" }
];
