// Vercel executes this function after the project build. The build bundles
// server.ts into dist/server.cjs, so the function must import the generated
// runtime artifact rather than the TypeScript source file (which is not part
// of the deployed function filesystem).
// @ts-expect-error dist/server.cjs is generated by the Vercel build command.
import app from "../dist/server.cjs";

export default app;
